#!/bin/bash
# Configure Railway CLI with Service ID for non-interactive access
# This script helps you set up Railway CLI access from Replit

set -e

echo "======================================"
echo "Railway CLI Configuration"
echo "======================================"
echo ""
echo "To get your SERVICE ID:"
echo "1. Go to Railway Dashboard: https://railway.app"
echo "2. Click on your project: resourceful-grace"
echo "3. Click on the 'keen-essence' (backend) service"
echo "4. Look at the URL in your browser:"
echo "   https://railway.app/project/<PROJECT_ID>/service/<SERVICE_ID>"
echo "5. Copy the SERVICE_ID (after '/service/')"
echo ""
echo "Example URL:"
echo "  https://railway.app/project/71558abf-25b0-4cb5-8233-fe6e685e0e93/service/abc123def-456-789"
echo "  SERVICE_ID = abc123def-456-789"
echo ""

read -p "Enter your SERVICE_ID: " SERVICE_ID

if [ -z "$SERVICE_ID" ]; then
    echo "❌ Error: SERVICE_ID cannot be empty"
    exit 1
fi

# Save to config file
CONFIG_FILE="scripts/.railway_config"
cat > "$CONFIG_FILE" << EOF
# Railway Configuration
# Auto-generated by configure_railway_cli.sh
PROJECT_ID="71558abf-25b0-4cb5-8233-fe6e685e0e93"
ENVIRONMENT="production"
SERVICE_ID="$SERVICE_ID"
SERVICE_NAME="keen-essence"
EOF

echo ""
echo "✅ Configuration saved to: $CONFIG_FILE"
echo ""
echo "Testing Railway CLI access..."
echo ""

# Test the configuration
export RAILWAY_TOKEN="${RAILWAY_TOKEN}"
if [ -z "$RAILWAY_TOKEN" ]; then
    echo "❌ Error: RAILWAY_TOKEN not found in environment"
    echo "Please set it in Replit Secrets"
    exit 1
fi

# Try to fetch logs
echo "Attempting to fetch logs..."
railway logs -s "$SERVICE_ID" -e production --lines 5 2>&1 || {
    echo ""
    echo "❌ Failed to fetch logs. Possible issues:"
    echo "  1. SERVICE_ID is incorrect"
    echo "  2. RAILWAY_TOKEN doesn't have access to this service"
    echo "  3. Network/API issue"
    echo ""
    echo "Please verify your SERVICE_ID and try again."
    exit 1
}

echo ""
echo "======================================"
echo "✅ Railway CLI configured successfully!"
echo "======================================"
echo ""
echo "You can now use:"
echo "  ./scripts/tail_backend_logs.sh"
echo "  ./scripts/get_railway_logs.sh"
echo ""
